### Crear un nuevo producto
@BASE_URL = http://localhost:3050
@productId = 682a5647aee16245150d9eb8

@supplierId = 682a5647aee16245150d9eb2
# Crear producto
POST {{BASE_URL}}/products
Content-Type: application/json

{
    "name": "El Principito 24",
    "price": 2500,
    "description": "Libro clásico de Antoine de Saint-Exupéry",
    "stock": 50,
    "category": "libro",
    "prueba": "prueba",
    "supplier": "{{supplierId}}"
}

### Obtener todos los productos
GET {{BASE_URL}}/products

### Obtener un producto por ID
GET {{BASE_URL}}/products/{{productId}}

### Actualizar un producto
PUT {{BASE_URL}}/products/{{productId}}
Content-Type: application/json

{
    "name": "El Principito Original",
    "price": 2800,
    "description": "Libro clásico de Antoine de Saint-Exupéry - Edición especial",
    "stock": 45,
    "category": "libro",
    "supplier": "{{supplierId}}"
}

### Eliminar un producto
DELETE {{BASE_URL}}/products/{{productId}}
