### Crear una nueva venta
@BASE_URL = http://localhost:3050
@productId = 6827a020fb2f9a649f1d4be6

@saleId = 682a576baee16245150d9eea

@startDate = 2024-05-18
@endDate = 2025-05-18

POST {{BASE_URL}}/sales
Content-Type: application/json

{
    "products": [
        {
            "product": "{{productId}}",
            "quantity": 1,
            "price": 2500
        }
    ],
    "customer": {
        "name": "Gustavo Baranda",
        "email": "Gustavo@example.com"
    }
}

### Obtener todas las ventas
GET {{BASE_URL}}/sales

### Obtener una venta por ID
GET {{BASE_URL}}/sales/{{saleId}}

### Obtener ventas por periodo de tiempo
GET {{BASE_URL}}/sales/reports/by-date?startDate={{startDate}}&endDate={{endDate}}

### Obtener ventas por semana o mes (week o month)
GET {{BASE_URL}}/sales/reports/by-period?period=week

### Obtener Productos más vendidos
GET {{BASE_URL}}/sales/reports/top-products

### Obtener Total de Ventas en Dinero
GET {{BASE_URL}}/sales/reports/total